name: Email Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f1001792@ds.study.iitm.ac.in
        run: echo "Hello, world! This step is named with my email."
