name: Combined Workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-workflow:
    name: CI with Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-f7d01d9

      - name: prime-cache-f7d01d9
        run: echo "Cache status :${{ steps.cache-deps.outputs.cache-hit }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

  email-workflow:
    name: Email Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f1001792@ds.study.iitm.ac.in
        run: echo "Hello, world! This step is named with my email."
